# Generated by Django 5.2 on 2025-04-11 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategorija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pavadinimas', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vieta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pavadinimas', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Inventorius',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pavadinimas', models.CharField(max_length=100)),
                ('serijinis_numeris', models.CharField(max_length=100, unique=True)),
                ('inventorinis_numeris', models.CharField(max_length=100)),
                ('kaina', models.DecimalField(decimal_places=2, max_digits=10)),
                ('busena', models.CharField(choices=[('Naudojamas', 'Naudojamas'), ('Sandeliuojamas', 'Sandeliuojamas'), ('Remontuojamas', 'Remontuojamas')], default='Naudojamas', max_length=50)),
                ('ivedimo_data', models.DateField(verbose_name='Įvedimo į eksploataciją data')),
                ('turto_tipas', models.CharField(choices=[('ILG', 'Ilgalaikis turtas'), ('TRU', 'Trumpalaikis turtas')], max_length=3)),
                ('kategorija', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventorius.kategorija')),
                ('vieta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventorius.vieta')),
            ],
        ),
    ]
